### ISSUE TITLE
[PROPOSAL] Add alias in config

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/MIMO#14]
A column could use an alias to be identified across multiple execution context 

```
version: "1"
metrics:
  - name: "person.phone"
    alias: "phone_number"
```
