### ISSUE TITLE
[PROPOSAL] Configure coherence source with template

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/MIMO#15]
```json
{"batchs":[{"id":1,"accounts":[{"number":"A"},{"number":"B"}]}]}
```

```yaml
version: "1"
metrics:
  - name: "batchs.[].accounts.[].number"
    coherentSource: "{{.current}} {{._1.id}}"
```

Path should be able to start from the current context of execution (inside an array structure for example)
- `.current` will reference the current object
- `.root` will reference the root object
- `._1` will reference the current first level object
- `._2` will reference the current second level object
- etc...
