### ISSUE TITLE
[PROPOSAL] Configuration profile

### ISSUE THREAD

**Issue by adrienaury** [CGI-FR/MIMO#6]
As a user of MIMO, I want to validate 

- a coherence rate between multiple real input fields vs the single pseudonym value 
- a masking rate with or without taking into account empty values
- constraints on any rate like : equals to 100%, greater or equals to 95%, ...

## Solution

Define a validation profile with a YAML configuration file:

**`mimo.yaml`**
```yaml
metrics:
  - name: # name of the field to validate
    exclude: [ nil, "" ] # exclude nil and empty values from the masking rate computation (default: only nil values)
    coherentWith: ["name", "surname"] # list of fields from witch the coherent rate is computed (default: the current field)
    constraints:
      maskingRate:
        shouldEqualsTo: 1
      coherentRate:
        shouldBeGreaterThan: 0.95
```

```console
$ mkfifo real.jsonl
$ lino pull bdd | tee real.jsonl | pimo | mimo --config mimo.yaml real.jsonl | lino push bdd
```
